# Astro 9

# Lecture 14: Intro to Linear Algebra

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy

## Examples: Matrices & Determinants

In [2]:
A = np.matrix([
    [0, 4],
    [2, 0]]
)
B = np.matrix(
    [[-1, 2],
     [1, -2]]
)

C = A + B
print("A=\n",A)
print("B=\n",B)
print("C=\n",C)
print("Determinant of C is", np.linalg.det(C))
D1 = A*B #([0*-1 + 4*1, 0*2 + 4*-2],[])
D2 = B*A #([-1*0 + 2*2, 2*0 + -2*2],[])
print("D1=\n",D1)
print("D2=\n",D2)

A=
 [[0 4]
 [2 0]]
B=
 [[-1  2]
 [ 1 -2]]
C=
 [[-1  6]
 [ 3 -2]]
Determinant of C is -16.000000000000007
D1=
 [[ 4 -8]
 [-2  4]]
D2=
 [[ 4 -4]
 [-4  4]]


In [3]:
det_c = (-1*-2) - (6*3)
print(det_c)

-16


## Inverting matrices

Linear systems of equations are of the form 

$$Av = b$$

where $A$ is a square matrix, $v$ is a vector of variables, and $b$ is a vector of values. This equation is solved by 
$$v = A^{-1}b$$

where $A^{-1}$ is the inverse of $A$, defined such that $AA^{-1} = A^{-1}A = I$, the identity matrix. Typically inverting a matrix is not the optimal numerical method for solving such problems, but there may be other occasions when inverting a matrix is necessary; the code below gives an example of how to compute the inverse of a matrix using the built-in function `np.linalg.inv`.

In [4]:
M = np.matrix(
[[10,-7,0],
[-3,2.099,6],
[5,-1,5]]  
)
print('We have matrix M = \n')
print(M)
Minv = np.linalg.inv(M)
print('\nIts inverse M^-1 = \n')
print(Minv)

We have matrix M = 

[[10.    -7.     0.   ]
 [-3.     2.099  6.   ]
 [ 5.    -1.     5.   ]]

Its inverse M^-1 = 

[[-1.09930023e-01 -2.33255581e-01  2.79906698e-01]
 [-2.99900033e-01 -3.33222259e-01  3.99866711e-01]
 [ 4.99500167e-02  1.66611130e-01  6.66444518e-05]]


Check that $AA^{-1} = A^{-1}A = I$

In [5]:
print(M*Minv, '\n\n', Minv*M)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  1.00000000e+00  1.93096407e-16]
 [ 6.93889390e-18  5.55111512e-17  1.00000000e+00]] 

 [[ 1.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00 -2.22044605e-16]
 [-2.41234983e-17  6.03358509e-17  1.00000000e+00]]


## Dot Products and Cross Products

### Dot Products

In [6]:
x = [4, 1, 6]
y = [3, 5, 7]

#dot_xy = 4*3 + 1*5 + 6*7
np.dot(x, y)

59

In [7]:
dot_xy = 4*3 + 1*5 + 6*7
dot_xy

59

In [10]:
a = np.matrix([[2, 2], [3, 1]])
b = np.matrix([[4, 3], [5, 2]])

#dot_ab = [[2*4 + 2*5, 2*3 + 2*2], [3*4 + 1*5, 3*3 + 1*2]] 
print(np.dot(a, b))
print(a*b)

[[18 10]
 [17 11]]
[[18 10]
 [17 11]]


In [9]:
dot_ab = [[2*4 + 2*5, 2*3 + 2*2], [3*4 + 1*5, 3*3 + 1*2]]
dot_ab

[[18, 10], [17, 11]]

### Cross Products

In [10]:
x = [4, 1, 6]
y = [3, 5, 7]
np.cross(x, y)

array([-23, -10,  17])

In [11]:
a = np.matrix([[2, 2, 2], [3, 1, 0]])
b = np.matrix([[4, 3, 1], [5, 2, 2]])


print(np.cross(a, b))

[[-4  6 -2]
 [ 2 -6  1]]


## Solving systems of linear equations

A typically more efficient way of solving the equation 

$$Av = b$$

is using Gaussian elimination, which is implemented in `np.linalg.solve` as below.

In [12]:
A = np.matrix(
[
    [25, 5, 1],
    [64, 8, 1],
    [144, 12, 1]
])

b = np.transpose(np.matrix([106.8, 177.2, 279.2])) # why do I need to transpose?

v = np.linalg.solve(A, b)
print("Solution: v=\n", v, "\n")
print("A * v = \n", A * v)

Solution: v=
 [[ 0.29047619]
 [19.69047619]
 [ 1.08571429]] 

A * v = 
 [[106.8]
 [177.2]
 [279.2]]


## Solving a System of Linear Equations Example

Lets solve the equations:

$4x  + 3y = 20$

$-5x + 9y = 26$

In [13]:
m_list = [[4, 3], [-5, 9]]
A = np.array(m_list)

inv_A = np.linalg.inv(A)

print(inv_A)

[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [14]:
B = np.array([20, 26])
X = np.linalg.inv(A).dot(B)

print(X)

[2. 4.]


In [15]:
#check our work
print(4*2 + 3*4)
print(-5*2 + 9*4)

20
26


Let's make it a little harder, solving three equations.

$4x + 3y + 2z = 25$

$-2x + 2y + 3z = -10$

$3x -5y + 2z = -4$

First we need to convert these equations into the form $$Av = b$$

In [16]:
#3X3 matrix of the coefficients of our variables
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
#Matrix of the other side of the equations
B = np.array([25, -10, -4])

#Now we can solve it just like before
X = np.linalg.inv(A).dot(B)

print(X)

[ 5.  3. -2.]


In [17]:
#Check our work
print(4*5 + 3*3 + 2*-2)
print(-2*5 + 2*3 + 3*-2)
print(3*5 - 5*3 + 2*-2)

25
-10
-4


## Real Life Example: Eigenvalue problem

### The eigenvalue problem ("diagonalization")

Probably one of the most famous problems in all of science is the eigenvalue problem. It is ubiquitous across fields and is the defining problem of quantum mechanics. In this problem, we change the problem slightly from before. For a given $A$, we try to look for scalar values $\lambda$ and vectors $v$ that satisfy the matrix equation

$$A v = \lambda v$$

Let us look at a simple example:
$$A = \begin{pmatrix}
0 & 1  \\
1 & 0 \\
\end{pmatrix}$$
The eigenvectors of this matrix are 
$$v_1 =  \frac{1}{\sqrt{2}}\begin{pmatrix}
1 \\
1 \\
\end{pmatrix}\text{ and }
v_2 = \frac{1}{\sqrt{2}}\begin{pmatrix}
1 \\
-1 \\
\end{pmatrix}$$
If you multiply $A$ by $v_1$ you get $Av_1 = v_1$ and if you multiply $A$ by $v_2$ you get $Av_2 = -v_2$ (check these for yourself by doing the multiplications). This means that the eigenvalue $\lambda_1$ corresponding to the eigenvector $v_1$ is $\lambda_1 = 1$, and the eigenvalue $\lambda_2$ corresponding to the eigenvector $v_2$ is $\lambda_2 = -1$.

One geometric intuition for what an eigenvector is that it is a vector whose direction is not changed by the action of $A$: only its length is rescaled by a factor of $\lambda$. 

An $m \times m$ matrix can have at most $m$ eigenvectors (and consequently it can have at most $m$ unique eigenvalues). It can also have $m$ eigenvectors but fewer than $m$ eigenvalues--that is, multiple eigenvectors may have the same eigenvalue (in physics, this is called "degeneracy").

This problem is referred to as "diagonalization" because once you have found all of the eigenvectors $v_i$ and their eigenvalues $\lambda_i$, you can decompose $A$ as
$$A = U D U^\dagger$$
where 
$$ D = \begin{pmatrix}
\lambda_1 & 0 & \cdots & 0 & 0 \\
0 & \lambda_2 & \cdots & 0 & 0 \\
\vdots & \vdots & \ddots & \vdots & \vdots\\
0 & 0 & 0 & \lambda_{m-1} & 0 \\
0 & 0 & \cdots & 0 & \lambda_m \\
\end{pmatrix}$$
and the columns of $U$ are formed by
$$U = \begin{pmatrix}
v_1 & v_2 & \cdots & v_{m-1} & v_m
\end{pmatrix}$$
(remember each $v_i$ is a column of $m$ elements). And $U^\dagger$ denotes the conjugate transpose of $U$. $D$ is a "diagonal" matrix becaues it has non-zero elements only along its diagonal, hence why this process is called "diagonalization".

It turns out that the determinant of a matrix, defined above, is also equal to the product of its eigenvalues.
$$\det(A) = \lambda_1 \times \lambda_2 \dots \times \lambda_m$$
So when $\det(A) = 0$ (the matrix is *singular*), this means that at least one eigenvalue is equal to zero.

### Finding eigenvectors and eigenvalues with numpy

In [27]:
A = np.matrix(
[
    [25, 5, 1],
    [64, 8, 1],
    [144, 12, 1]
])

In [28]:
w,v = np.linalg.eig(A)
print('Eigenvalues of A=',w)
print('Eigenvectors: \n',v)

Eigenvalues of A= [40.01957922 -6.35011985  0.33054063]
Eigenvectors: 
 [[-0.20222943 -0.06964965  0.01954073]
 [-0.43166576  0.24321109 -0.28790386]
 [-0.8790722   0.96746953  0.95745994]]


In [29]:
v_1 = np.transpose(np.matrix([-0.20222943, -0.43166576, -0.8790722]))

D = A*v_1
print(D)
print(D/40.01957922)

[[ -8.09313675]
 [-17.2750818 ]
 [-35.18009924]]
[[-0.20222943]
 [-0.43166575]
 [-0.87907219]]


In [30]:
det_A = np.linalg.det(A)
print('Determinant of A:', det_A)

eig_mult = w[0] * w[1] * w[2]
print('Multiples of Eigenvalues:', eig_mult)

Determinant of A: -83.99999999999999
Multiples of Eigenvalues: -83.9999999999999


In [31]:
S = np.matrix(
[
    [0,1],
    [1,0]
])
w,v = np.linalg.eig(S)
print('Eigenvalues of S=',w)
print('Eigenvectors: \n',v)

Eigenvalues of S= [ 1. -1.]
Eigenvectors: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [32]:
print(1/np.sqrt(2)) #electron spin

0.7071067811865475
